name: JCFUtils
main: org.pale.jcfutils.Plugin
version: 1.1
api-version: 1.13
commands:
  jcfutils:
    description: JCFUtils configuration command
    aliases: [jcf]
    usage: /jcfutils
    permission: jcfutils
